name: Build .exe Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Create .exe file
        run: |
          pyinstaller --onefile --windowed posture_monitor.py
          
      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v2
        with:
          name: posture-monitor-exe
          path: dist/posture_monitor.exe
